return {
    MC_POST_DONATION_SLOT_DESTROYED = "MC_POST_DONATION_SLOT_DESTROYED",
    MC_PRE_DONATION_SLOT_COIN_INSERTED = "MC_PRE_DONATION_SLOT_COIN_INSERTED",
    MC_POST_DONATION_SLOT_COIN_INSERTED = "MC_PRE_DONATION_SLOT_COIN_INSERTED"
}
