local Pool = require("src/pools/pool")

return {
    [ItemPoolType.POOL_TREASURE] = Pool:new(ItemPoolType.POOL_TREASURE, 1),
    [ItemPoolType.POOL_SHOP] = Pool:new(ItemPoolType.POOL_SHOP, 0.5),
    [ItemPoolType.POOL_LIBRARY] = Pool:new(ItemPoolType.POOL_LIBRARY, 0.1),
    [ItemPoolType.POOL_CURSE] = Pool:new(ItemPoolType.POOL_CURSE, 0.5),
    [ItemPoolType.POOL_BOSS] = Pool:new(ItemPoolType.POOL_BOSS, 1),
    [ItemPoolType.POOL_SECRET] = Pool:new(ItemPoolType.POOL_SECRET, 1),
    [ItemPoolType.POOL_DEVIL] = Pool:new(ItemPoolType.POOL_DEVIL, 1),
    [ItemPoolType.POOL_ANGEL] = Pool:new(ItemPoolType.POOL_ANGEL, 1),
    [ItemPoolType.POOL_GOLDEN_CHEST] = Pool:new(ItemPoolType.POOL_GOLDEN_CHEST, 0.4),
    [ItemPoolType.POOL_RED_CHEST] = Pool:new(ItemPoolType.POOL_RED_CHEST, 0.4),
    [ItemPoolType.POOL_DEMON_BEGGAR] = Pool:new(ItemPoolType.POOL_DEMON_BEGGAR, 0.5),
    [ItemPoolType.POOL_BOMB_BUM] = Pool:new(ItemPoolType.POOL_BOMB_BUM, 0.5),
    [ItemPoolType.POOL_KEY_MASTER] = Pool:new(ItemPoolType.POOL_KEY_MASTER, 0.5),
    [ItemPoolType.POOL_ROTTEN_BEGGAR] = Pool:new(ItemPoolType.POOL_ROTTEN_BEGGAR, 1),
    [ItemPoolType.POOL_BATTERY_BUM] = Pool:new(ItemPoolType.POOL_BATTERY_BUM, 1),
    [ItemPoolType.POOL_OLD_CHEST] = Pool:new(ItemPoolType.POOL_OLD_CHEST, 0.4),
    [ItemPoolType.POOL_MOMS_CHEST] = Pool:new(ItemPoolType.POOL_MOMS_CHEST, 0.5),
    [ItemPoolType.POOL_BABY_SHOP] = Pool:new(ItemPoolType.POOL_BABY_SHOP, 1),
    [ItemPoolType.POOL_GREED_TREASURE] = Pool:new(ItemPoolType.POOL_GREED_TREASURE, 1),
    [ItemPoolType.POOL_GREED_SHOP] = Pool:new(ItemPoolType.POOL_GREED_SHOP, 0.5),
    [ItemPoolType.POOL_GREED_CURSE] = Pool:new(ItemPoolType.POOL_GREED_CURSE, 0.5),
    [ItemPoolType.POOL_GREED_BOSS] = Pool:new(ItemPoolType.POOL_GREED_BOSS, 1),
    [ItemPoolType.POOL_GREED_SECRET] = Pool:new(ItemPoolType.POOL_GREED_SECRET, 1),
    [ItemPoolType.POOL_GREED_DEVIL] = Pool:new(ItemPoolType.POOL_GREED_DEVIL, 1),
    [ItemPoolType.POOL_GREED_ANGEL] = Pool:new(ItemPoolType.POOL_GREED_ANGEL, 1),
    [ItemPoolType.POOL_WOODEN_CHEST] = Pool:new(ItemPoolType.POOL_WOODEN_CHEST, 1),
    [ItemPoolType.POOL_PLANETARIUM] = Pool:new(ItemPoolType.POOL_PLANETARIUM, 1),
    [ItemPoolType.POOL_SHELL_GAME] = Pool:new(ItemPoolType.POOL_SHELL_GAME, 1),
    [ItemPoolType.POOL_BEGGAR] = Pool:new(ItemPoolType.POOL_BEGGAR, 0.5),
    [ItemPoolType.POOL_DEMON_BEGGAR] = Pool:new(ItemPoolType.POOL_DEMON_BEGGAR, 0.5),
    [ItemPoolType.POOL_ULTRA_SECRET] = Pool:new(ItemPoolType.POOL_ULTRA_SECRET, 0.4),
    [ItemPoolType.POOL_CRANE_GAME] = Pool:new(ItemPoolType.POOL_CRANE_GAME, 0.1),
}
